version: '3'

services: 
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    ports: 
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    
  